language: ruby
cache:
- bundler
rvm:
- 2.3.4
env:
  global:
  - CC_TEST_REPORTER_ID=23873bc8aee722ae9dcccaeeb18b97f0a830b50ba16d6d25ec0f67619902b5ef
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle exec rails db:create RAILS_ENV=test
- bundle exec rails db:migrate RAILS_ENV=test
- bundle exec rspec
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: hgv2f4xSu8Pk9gooLTPrPZcaHspMxMPbvZ4Kbmet1zeEmKSyE7WQlU5YTJIMA4vO6jYIpi107awFBJiKJrzZ57D45iEAxw/4amhUE69Ty50OLf3LfXCHuYSBWeubpqXqNgQxXnk2pxs6QnKKwyTEW4fzWCcF7hSZG3JnhgRr5WoFc+QFH4BAfifSE8XS3rZpuDLCjNzbqgv/DRNi9zFAdPrcnvV1Kal+ylbaIt3Ndmx/zOrJFKzi8d+bbS+u2xjo7pD9fN1aVtPxbr6G7pZWy5ffXfLcKTDi3pQVxoPxbkKiqzRjLEQMkQ35T9EPejibY6qIm/Nnab2DL+ovzqhMF6GrU9OJ08yizZbPqbmVeQKtlqCx41+RWNIDtxwuCb18K710CJRtsKpCl+/oQ/K7jPKEeuFbsOhfo7rNz5fzcxO8k/Iq2ZxONgME4Ljgo4fCViNo85Lw0vHwlNocDbELOMeS3gBprsPHvybfCKhxG/YLYieG6frL+/oUEF1LH1QTc62Rim8hOPtR81pHbXf4dDTbJ0kxMShNg3fgf41sGwwIXYXEHmnsyWXrnPC2rexzOTW5cbaEGZZtrrZzgZqSmA0H4BhgHeGWXew/+ZBTnnfSTGFvQN9oYfjPiOgEY8ezPAws0idROIj2LR6/9tzAAVdJ+Rb/tTWZFJmm6UlVkRM=
  app: silvertuna-staging
  on:
    repo: hyrumcarlile/devSR
notifications:
  email: false
