# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afef4d2a7971fea9e76e307afa6e4261521013f2c43da82c10c19de6f0fcef1a3471679bf84f57f59b9a0c5c65f81854551eeea668b39919a0b668ccd326719c

test:
  secret_key_base: 7b1b0e31eabbf3d5f3722c81f9bff7db7aed4dab2a4ebe8d5c7cb2285cf34488c1247a968f0f41b57fe73e3931a1a4c3a6052c2dd4293ac970dbdff1cb2e6cb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
